import { DEMO_ADMIN_ID, demoProfile } from "@/lib/auth/current-user";
import type { AppStore, Athlete, AthleteLeak, AthleteOpportunity, Buildout, BuildoutTask, Diagnostic, DiagnosticScore, Offer, PipelineDeal, Report } from "@/types/domain";

const t0 = "2026-05-27T16:00:00.000Z";

export const athleteIds = {
  nico: "00000000-0000-4000-8000-000000000042",
  marcus: "00000000-0000-4000-8000-000000000029",
  devon: "00000000-0000-4000-8000-000000000017",
  jalen: "00000000-0000-4000-8000-000000000061",
  isaiah: "00000000-0000-4000-8000-000000000083",
  adrian: "00000000-0000-4000-8000-000000000094",
};

export const buildoutIds = {
  nico: "10000000-0000-4000-8000-000000000042",
  marcus: "10000000-0000-4000-8000-000000000029",
  devon: "10000000-0000-4000-8000-000000000017",
  jalen: "10000000-0000-4000-8000-000000000061",
  isaiah: "10000000-0000-4000-8000-000000000083",
  adrian: "10000000-0000-4000-8000-000000000094",
};

const athletes: Athlete[] = [
  {
    id: athleteIds.nico,
    code: "NR-042",
    name: "Nico Ramirez",
    sport: "Combat Sports",
    level: "Professional",
    audience_count: 112000,
    audience_label: "112K",
    platforms: ["IG", "YT", "X"],
    source: "RRU - Tyler Direct",
    owner: "AID",
    stage: "Buildout Proposal",
    stage_index: 4,
    readiness_score: 81,
    brand_summary: "Disciplined professional fighter. Storyteller of the grind. Resonates with high-performing men 28-45.",
    monetization_summary: "Single sponsor deal at $4K per quarter. No owned audience. No CTA path.",
    audience_behavior: "70% male, US/MX/CA. Engages with structure, conditioning, and mindset content.",
    trust_signals: ["7-year pro record", "12 main-card features", "Featured in 3 documentaries"],
    inbound_questions: ["What is your training split?", "Coaching available?", "What do you eat?"],
    assets: ["IG 112K", "YT 38K", "X 14K", "Email list: 1,800"],
    current_leak: "Strong identity, no first-offer path. Inbound DMs going unmonetized.",
    next_action: "Approve buildout proposal - $18,500 scope",
    pipeline_value: 18500,
    avatar_initials: "NR",
    archived_at: null,
    created_at: t0,
    updated_at: t0,
  },
  {
    id: athleteIds.marcus,
    code: "MK-029",
    name: "Marcus King",
    sport: "Baseball",
    level: "MLB",
    audience_count: 84000,
    audience_label: "84K",
    platforms: ["IG", "X", "TikTok"],
    source: "RRU - Road Haus",
    owner: "AID",
    stage: "First Offer Design",
    stage_index: 3,
    readiness_score: 74,
    brand_summary: "Veteran utility infielder. Family man. Faith-forward. Hitting-IQ educator.",
    monetization_summary: "Two endorsements at $60K per year combined. No DTC product. No list.",
    audience_behavior: "55% male 30-50, parent demographic, baseball families.",
    trust_signals: ["9 MLB seasons", "Hitting clinic alumni 240+", "Father-coach community"],
    inbound_questions: ["Do you do clinics?", "Can my son train with you?", "Hitting drill recommendations?"],
    assets: ["IG 84K", "X 22K", "TikTok 11K", "Coaching alumni list"],
    current_leak: "Strong inbound from kids and parents. No youth product. Sponsorships static.",
    next_action: "Finalize first-offer mechanic - youth hitting cohort",
    pipeline_value: 14200,
    avatar_initials: "MK",
    archived_at: null,
    created_at: t0,
    updated_at: t0,
  },
  {
    id: athleteIds.devon,
    code: "DP-017",
    name: "Devon Price",
    sport: "Retired Athlete",
    level: "Founder",
    audience_count: 26000,
    audience_label: "26K",
    platforms: ["LinkedIn", "X", "Substack"],
    source: "RRU - Founder Network",
    owner: "RRU",
    stage: "Funnel Build",
    stage_index: 4,
    readiness_score: 67,
    brand_summary: "Ex-pro turned founder. Operator's voice. Wealth and business literacy for athletes.",
    monetization_summary: "Speaking at $8K per event. One-to-one advisory is ad hoc. No productized offer.",
    audience_behavior: "Investors, athletes, operators, and founders. High-comment threads around ownership and access.",
    trust_signals: ["Founder network", "Private investor rooms", "Speaking proof"],
    inbound_questions: ["Can you advise our group?", "Do you invest with athletes?", "How do players avoid bad deals?"],
    assets: ["LinkedIn 19K", "X 7K", "Substack 3K"],
    current_leak: "Advisory demand exists, but there is no discovery-call funnel.",
    next_action: "Deploy lead-magnet to discovery-call funnel",
    pipeline_value: 12000,
    avatar_initials: "DP",
    archived_at: null,
    created_at: t0,
    updated_at: t0,
  },
  {
    id: athleteIds.jalen,
    code: "JT-061",
    name: "Jalen Torres",
    sport: "Football",
    level: "NCAA D1",
    audience_count: 42000,
    audience_label: "42K",
    platforms: ["IG", "TikTok"],
    source: "RRU - Combine Network",
    owner: "AID",
    stage: "Complete Diagnostic",
    stage_index: 2,
    readiness_score: 58,
    brand_summary: "Starting LB. Energy, work ethic, region-loyal Texas audience. Recruiter-magnet content.",
    monetization_summary: "Three NIL deals at $22K total to date. Local restaurant partnership.",
    audience_behavior: "Parents, high school athletes, and regional fans. Strong saves on training content.",
    trust_signals: ["D1 starter", "Regional recruiting pull", "Combine network"],
    inbound_questions: ["How do I get recruited?", "What camps matter?", "Can you review film?"],
    assets: ["IG 31K", "TikTok 11K"],
    current_leak: "Zero owned audience capture and no defined commercial offer.",
    next_action: "Complete diagnostic - schedule discovery call",
    pipeline_value: 6800,
    avatar_initials: "JT",
    archived_at: null,
    created_at: t0,
    updated_at: t0,
  },
  {
    id: athleteIds.isaiah,
    code: "IB-083",
    name: "Isaiah Brooks",
    sport: "Basketball",
    level: "Overseas Pro",
    audience_count: 61000,
    audience_label: "61K",
    platforms: ["IG", "YT", "TikTok"],
    source: "RRU - Premium Rooms",
    owner: "AID",
    stage: "Sponsorship Path Map",
    stage_index: 3,
    readiness_score: 63,
    brand_summary: "International hooper. Travel-storyteller. Aspirational, polished, business-minded.",
    monetization_summary: "Sponsors at $45K per year. No direct-to-consumer offer. No list capture.",
    audience_behavior: "Travel-engaged basketball audience with strong replies around overseas path questions.",
    trust_signals: ["Overseas pro", "Travel content proof", "Sponsor history"],
    inbound_questions: ["How do you play overseas?", "What agents are real?", "How much can players make?"],
    assets: ["IG 45K", "YT 9K", "TikTok 7K"],
    current_leak: "Sponsor rate is not structured and no information product exists.",
    next_action: "Map sponsorship architecture and rate card",
    pipeline_value: 9400,
    avatar_initials: "IB",
    archived_at: null,
    created_at: t0,
    updated_at: t0,
  },
  {
    id: athleteIds.adrian,
    code: "AC-094",
    name: "Adrian Cole",
    sport: "Baseball",
    level: "MiLB AA",
    audience_count: 18000,
    audience_label: "18K",
    platforms: ["IG"],
    source: "RRU - Agency Intro",
    owner: "AID",
    stage: "Audience Capture",
    stage_index: 1,
    readiness_score: 49,
    brand_summary: "Hard-working AA pitcher. Faith and family. Process over hype.",
    monetization_summary: "None. No deals. No product.",
    audience_behavior: "Small but loyal audience around recovery, faith, and family.",
    trust_signals: ["AA pitcher", "Agency intro", "Faith-first community"],
    inbound_questions: ["What is your recovery routine?", "How do you stay consistent?", "Do you mentor?"],
    assets: ["IG 18K"],
    current_leak: "No audience capture and no defined identity for monetization.",
    next_action: "Audience capture mechanic and identity narrative",
    pipeline_value: 3500,
    avatar_initials: "AC",
    archived_at: null,
    created_at: t0,
    updated_at: t0,
  },
];

const leakSeeds: Array<[string, string, AthleteLeak["severity"]]> = [
  [athleteIds.nico, "No first transaction path", "high"],
  [athleteIds.nico, "Email list growing 4% with no capture mechanism", "high"],
  [athleteIds.nico, "DM volume unmanaged, estimated 90 per week", "medium"],
  [athleteIds.marcus, "Youth demand uncaptured", "high"],
  [athleteIds.marcus, "No digital product despite clear path", "high"],
  [athleteIds.marcus, "Sponsor stack flat for 3 years", "medium"],
  [athleteIds.devon, "Advisory demand unmonetized", "high"],
  [athleteIds.devon, "No discovery-call funnel", "high"],
  [athleteIds.devon, "Substack monetization paused", "low"],
  [athleteIds.jalen, "Zero owned audience capture", "high"],
  [athleteIds.jalen, "No defined commercial offer", "high"],
  [athleteIds.jalen, "NIL deals reactive, not strategic", "medium"],
  [athleteIds.isaiah, "Sponsor rate not structured", "high"],
  [athleteIds.isaiah, "No information product", "medium"],
  [athleteIds.isaiah, "Audience travel-engaged, not monetized", "medium"],
  [athleteIds.adrian, "Zero audience capture", "high"],
  [athleteIds.adrian, "No defined identity for monetization", "high"],
  [athleteIds.adrian, "Pre-product stage", "medium"],
];

const opportunitySeeds: Array<[string, string]> = [
  [athleteIds.nico, "21-Day Performance Reset"],
  [athleteIds.nico, "Recurring Performance Community"],
  [athleteIds.nico, "Sponsorship Architecture"],
  [athleteIds.nico, "Founder Equity Path"],
  [athleteIds.marcus, "Youth Hitting Cohort"],
  [athleteIds.marcus, "Parent Coach Community"],
  [athleteIds.marcus, "NIL-Compliant Camp"],
  [athleteIds.marcus, "Branded Equipment Drop"],
  [athleteIds.devon, "Advisory Cohort"],
  [athleteIds.devon, "Wealth-Lit Community"],
  [athleteIds.devon, "Founder Equity Syndicate"],
  [athleteIds.jalen, "Recruiting-Path Cohort"],
  [athleteIds.jalen, "Camp Series"],
  [athleteIds.jalen, "NIL Apparel Drop"],
  [athleteIds.isaiah, "Overseas-Path Guide"],
  [athleteIds.isaiah, "Travel-Brand Activation"],
  [athleteIds.isaiah, "Sponsorship Tier Architecture"],
  [athleteIds.adrian, "Audience Capture Lead Magnet"],
  [athleteIds.adrian, "Faith-First Athlete Community"],
];

const offers: Offer[] = [
  {
    id: "20000000-0000-4000-8000-000000000042",
    athlete_id: athleteIds.nico,
    name: "Fight Shape Reset",
    price: 297,
    buyer_profile: "High-performing men 28-45 who want fighter-level structure without joining a fight gym.",
    promise: "A 21-day fighter-inspired reset that restores training consistency, nutrition rhythm, and identity.",
    mechanism: "Daily protocol, weekly check-in, short-form demonstration assets, and a private completion track.",
    deliverables: {
      items: ["21-day training protocol", "Nutrition rhythm guide", "Weekly check-in form", "Completion badge"],
      risk_reversal: "Refund if the buyer completes seven days and does not receive a usable training rhythm.",
      proof_assets_needed: ["Nico transformation reel", "Training split walkthrough", "Three buyer screenshots"],
    },
    projected_month_1_revenue: 47000,
    status: "approved",
    created_by: DEMO_ADMIN_ID,
    created_at: t0,
    updated_at: t0,
  },
  {
    id: "20000000-0000-4000-8000-000000000029",
    athlete_id: athleteIds.marcus,
    name: "Hitting IQ - Father/Son Cohort",
    price: 497,
    buyer_profile: "Baseball parents with sons age 10-16 who want a smarter hitting plan.",
    promise: "A four-week cohort that helps parent and player understand hitting decisions, drills, and practice rhythm.",
    mechanism: "Weekly live teaching, drill library, parent playbook, and final swing review.",
    deliverables: {
      items: ["4 cohort calls", "Hitting IQ workbook", "Swing review template", "Parent practice calendar"],
      risk_reversal: "First-call satisfaction guarantee.",
      proof_assets_needed: ["Clinic clips", "Alumni parent quotes"],
    },
    projected_month_1_revenue: 38000,
    status: "review",
    created_by: DEMO_ADMIN_ID,
    created_at: t0,
    updated_at: t0,
  },
  {
    id: "20000000-0000-4000-8000-000000000017",
    athlete_id: athleteIds.devon,
    name: "Athlete Operator - Quarterly Advisory",
    price: 4500,
    buyer_profile: "Active and retired athletes building companies, partnerships, or investment access.",
    promise: "A 90-day advisory container for athletes turning access into operating assets.",
    mechanism: "Diagnostic, deal-room map, weekly office hours, and operator action plan.",
    deliverables: {
      items: ["90-day advisory plan", "Deal-room map", "Weekly office hours", "Operator scorecard"],
      risk_reversal: "First two-week fit check before the quarter locks.",
      proof_assets_needed: ["Founder case study", "Investor-room screenshots"],
    },
    projected_month_1_revenue: 27000,
    status: "deployed",
    created_by: DEMO_ADMIN_ID,
    created_at: t0,
    updated_at: t0,
  },
];

const buildouts: Buildout[] = [
  { id: buildoutIds.nico, athlete_id: athleteIds.nico, stage: 4, percent_complete: 62, owner: "AID", blocker: null, risk_level: "high", next_action: "Approve scope and deploy CTA path", status: "active", created_at: t0, updated_at: t0 },
  { id: buildoutIds.marcus, athlete_id: athleteIds.marcus, stage: 3, percent_complete: 38, owner: "AID", blocker: "Pricing review pending operator sign-off", risk_level: "high", next_action: "Lock cohort cap and price", status: "blocked", created_at: t0, updated_at: t0 },
  { id: buildoutIds.devon, athlete_id: athleteIds.devon, stage: 4, percent_complete: 71, owner: "RRU", blocker: "Email warm-up stalled day 4", risk_level: "medium", next_action: "Finish discovery-call page QA", status: "active", created_at: t0, updated_at: t0 },
  { id: buildoutIds.jalen, athlete_id: athleteIds.jalen, stage: 2, percent_complete: 24, owner: "AID", blocker: "CTA path undeployed", risk_level: "high", next_action: "Complete diagnostic and capture mechanic", status: "active", created_at: t0, updated_at: t0 },
  { id: buildoutIds.isaiah, athlete_id: athleteIds.isaiah, stage: 3, percent_complete: 41, owner: "AID", blocker: null, risk_level: "medium", next_action: "Build sponsor tier map", status: "active", created_at: t0, updated_at: t0 },
  { id: buildoutIds.adrian, athlete_id: athleteIds.adrian, stage: 1, percent_complete: 12, owner: "AID", blocker: null, risk_level: "medium", next_action: "Define identity and lead magnet", status: "not_started", created_at: t0, updated_at: t0 },
];

const pipelineDeals: PipelineDeal[] = [
  { id: "30000000-0000-4000-8000-000000000042", athlete_id: athleteIds.nico, deal_name: "Nico Ramirez Buildout Scope", deal_type: "Infrastructure Buildout", amount: 18500, probability: 82, stage: "Buildout Proposed", expected_close_date: "2026-06-07", owner_id: DEMO_ADMIN_ID, created_at: t0, updated_at: t0 },
  { id: "30000000-0000-4000-8000-000000000029", athlete_id: athleteIds.marcus, deal_name: "Marcus King First Offer Buildout", deal_type: "Infrastructure Buildout", amount: 14200, probability: 68, stage: "Diagnostic Sold", expected_close_date: "2026-06-12", owner_id: DEMO_ADMIN_ID, created_at: t0, updated_at: t0 },
  { id: "30000000-0000-4000-8000-000000000017", athlete_id: athleteIds.devon, deal_name: "Devon Price Funnel Completion", deal_type: "Ongoing Optimization", amount: 12000, probability: 74, stage: "Active Fulfillment", expected_close_date: "2026-06-04", owner_id: DEMO_ADMIN_ID, created_at: t0, updated_at: t0 },
  { id: "30000000-0000-4000-8000-000000000061", athlete_id: athleteIds.jalen, deal_name: "Jalen Torres Diagnostic", deal_type: "Revenue Diagnostic", amount: 6800, probability: 46, stage: "Qualified", expected_close_date: "2026-06-18", owner_id: DEMO_ADMIN_ID, created_at: t0, updated_at: t0 },
  { id: "30000000-0000-4000-8000-000000000083", athlete_id: athleteIds.isaiah, deal_name: "Isaiah Brooks Sponsorship Map", deal_type: "Strategic Map", amount: 9400, probability: 58, stage: "Buildout Proposed", expected_close_date: "2026-06-21", owner_id: DEMO_ADMIN_ID, created_at: t0, updated_at: t0 },
];

const reports: Report[] = [
  {
    id: "40000000-0000-4000-8000-000000000042",
    athlete_id: athleteIds.nico,
    report_type: "Athlete Revenue Infrastructure Audit",
    title: "Nico Ramirez Revenue Infrastructure Audit",
    status: "approved",
    content: {
      summary: "Nico has the strongest near-term buildout case in the pilot cohort. The audience trusts his discipline, but the current path has no first transaction or follow-up engine.",
      sections: [
        { title: "Primary Revenue Leak", body: "Inbound DMs and list growth are not connected to a first paid offer.", bullets: ["No visible CTA path", "Email list is not used for launch warm-up", "Sponsor proof is not converted into buyer proof"] },
        { title: "Recommended Path", body: "Approve Fight Shape Reset, deploy capture, and launch to the warm audience inside a 30-day buildout." },
      ],
      metrics: { readiness_score: 81, projected_month_1_revenue: 47000, pipeline_value: 18500 },
    },
    pdf_url: null,
    created_by: DEMO_ADMIN_ID,
    created_at: t0,
    updated_at: t0,
  },
  {
    id: "40000000-0000-4000-8000-000000000029",
    athlete_id: athleteIds.marcus,
    report_type: "First Offer Recommendation",
    title: "Marcus King First Offer Recommendation",
    status: "draft",
    content: {
      summary: "Marcus should package parent and youth demand into a capped father/son hitting cohort before sponsor negotiations resume.",
      sections: [
        { title: "Buyer", body: "Baseball parents who already ask for clinics, drills, and swing feedback." },
        { title: "Offer", body: "Four-week cohort at $497 with live teaching, drill library, and a final swing review." },
      ],
      metrics: { price: 497, projected_month_1_revenue: 38000 },
    },
    pdf_url: null,
    created_by: DEMO_ADMIN_ID,
    created_at: t0,
    updated_at: t0,
  },
];

export function createSeedStore(): AppStore {
  const diagnostics: Diagnostic[] = athletes.slice(0, 4).map((athlete, index) => ({
    id: `50000000-0000-4000-8000-0000000000${index + 10}`,
    athlete_id: athlete.id,
    status: index === 0 ? "approved" : "complete",
    overall_score: athlete.readiness_score,
    summary: `${athlete.name} has meaningful attention and trust, but revenue infrastructure is incomplete.`,
    primary_constraint: athlete.current_leak,
    recommended_path: athlete.next_action,
    created_by: DEMO_ADMIN_ID,
    created_at: t0,
    updated_at: t0,
  }));

  const diagnosticScores: DiagnosticScore[] = diagnostics.flatMap((diagnostic, index) => {
    const base = athletes.find((athlete) => athlete.id === diagnostic.athlete_id)?.readiness_score || 60;
    const categories = [
      "Audience Quality",
      "Brand Authority",
      "Commercial Intent",
      "Offer Clarity",
      "CTA Path",
      "Capture Infrastructure",
      "Follow-Up Infrastructure",
      "Proof Assets",
      "Content-to-Commerce Fit",
      "Ownership Potential",
      "Revenue Stability",
    ];

    return categories.map((category, scoreIndex) => {
      const structuralPenalty = ["Offer Clarity", "CTA Path", "Capture Infrastructure", "Follow-Up Infrastructure"].includes(category) ? 34 : 0;
      const score = Math.max(14, Math.min(94, base - structuralPenalty + ((scoreIndex * 7 + index * 3) % 18) - 6));
      return {
        id: `51000000-0000-4000-8000-${String(index + 1).padStart(4, "0")}${String(scoreIndex + 1).padStart(8, "0")}`,
        diagnostic_id: diagnostic.id,
        category,
        score,
        severity: score < 35 ? "critical" : score < 55 ? "high" : score < 72 ? "medium" : "low",
        note: score < 55 ? `${category} is constraining the revenue path.` : `${category} supports the current buildout path.`,
      };
    });
  });

  const athleteLeaks: AthleteLeak[] = leakSeeds.map(([athlete_id, label, severity], index) => ({
    id: `60000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
    athlete_id,
    label,
    severity,
    created_at: t0,
  }));

  const athleteOpportunities: AthleteOpportunity[] = opportunitySeeds.map(([athlete_id, label], index) => ({
    id: `61000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
    athlete_id,
    label,
    created_at: t0,
  }));

  const buildoutTasks: BuildoutTask[] = [
    { id: "70000000-0000-4000-8000-000000000001", buildout_id: buildoutIds.nico, title: "Approve buildout scope", description: "Confirm price, deliverables, and launch window with Tyler.", status: "doing", assignee_id: DEMO_ADMIN_ID, due_date: "2026-06-03", created_at: t0, updated_at: t0 },
    { id: "70000000-0000-4000-8000-000000000002", buildout_id: buildoutIds.nico, title: "Draft launch CTA", description: "Create the CTA and payment path copy for Fight Shape Reset.", status: "todo", assignee_id: DEMO_ADMIN_ID, due_date: "2026-06-05", created_at: t0, updated_at: t0 },
    { id: "70000000-0000-4000-8000-000000000003", buildout_id: buildoutIds.marcus, title: "Finalize cohort price", description: "Set cap, price, and call cadence.", status: "blocked", assignee_id: DEMO_ADMIN_ID, due_date: "2026-06-04", created_at: t0, updated_at: t0 },
    { id: "70000000-0000-4000-8000-000000000004", buildout_id: buildoutIds.devon, title: "QA discovery page", description: "Finish page copy and form routing.", status: "doing", assignee_id: DEMO_ADMIN_ID, due_date: "2026-06-02", created_at: t0, updated_at: t0 },
  ];

  return {
    profiles: [demoProfile],
    athletes,
    athlete_leaks: athleteLeaks,
    athlete_opportunities: athleteOpportunities,
    diagnostics,
    diagnostic_scores: diagnosticScores,
    offers,
    buildouts,
    buildout_tasks: buildoutTasks,
    pipeline_deals: pipelineDeals,
    reports,
    agent_threads: [
      {
        id: "80000000-0000-4000-8000-000000000001",
        title: "Pilot Cohort Command Thread",
        created_by: DEMO_ADMIN_ID,
        created_at: t0,
        updated_at: t0,
      },
    ],
    agent_messages: [
      {
        id: "81000000-0000-4000-8000-000000000001",
        thread_id: "80000000-0000-4000-8000-000000000001",
        role: "assistant",
        content: "Prototype Mode fallback context loaded. Pilot cohort: 6 seeded athletes, 4 diagnostics, 6 buildouts, and 5 pipeline deals.",
        metadata: { mode: "prototype" },
        created_at: t0,
      },
    ],
    activity_log: [
      { id: "90000000-0000-4000-8000-000000000001", actor_id: DEMO_ADMIN_ID, entity_type: "athlete", entity_id: athleteIds.nico, action: "athlete.created", metadata: { source: "seed" }, created_at: t0 },
      { id: "90000000-0000-4000-8000-000000000002", actor_id: DEMO_ADMIN_ID, entity_type: "diagnostic", entity_id: "50000000-0000-4000-8000-000000000010", action: "diagnostic.approved", metadata: { source: "seed" }, created_at: t0 },
      { id: "90000000-0000-4000-8000-000000000003", actor_id: DEMO_ADMIN_ID, entity_type: "offer", entity_id: "20000000-0000-4000-8000-000000000042", action: "offer.approved", metadata: { source: "seed" }, created_at: t0 },
      { id: "90000000-0000-4000-8000-000000000004", actor_id: DEMO_ADMIN_ID, entity_type: "buildout", entity_id: buildoutIds.marcus, action: "buildout.blocked", metadata: { blocker: "Pricing review pending operator sign-off" }, created_at: t0 },
    ],
    files: [],
  };
}
